name: Frontend CI

on:
  pull_request:
    branches: [dev-fe, dev]

jobs:
  build:
    name: Static Test and Pre-build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "none"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

      - name: Run Prettier
        run: pnpm format --check

      - name: Run TypeScript for type check
        run: pnpm tsc --noEmit

      - name: Run Vitest & Testing-library
        run: pnpm vitest

      - name: Pre-Build Project
        run: pnpm build
